version: "17.0.0"
services:
  postgres17:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=24823972
      - POSTGRES_USER=root
      - POSTGRES_DB=nestjs
  
  pgadmin4:
    image: dpage/pgadmin4
    ports: 
      - 5050:80
    links:
      - postgres17
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=12345678